const users = [
  {
    fname: "Ashok",
    lname: "Sharma",
    email: "ashok@gmail.com",
    password: "helloworldashok",
    role: "admin",
  },
  {
    fname: "Palak",
    lname: "Sharma",
    email: "palak@yahoo.com",
    password: "helloworldpalak",
    salary: 36000,
    role: "employee",
    department_id: 1,
  },
  {
    fname: "Raj",
    lname: "Lakhani",
    email: "raj@gmail.com",
    password: "helloworldraj",
    salary: 60000,
    role: "employee",
    department: 2,
  },
  {
    fname: "Priya",
    lname: "Singh",
    email: "priya.singh@example.com",
    password: "helloworldPriya",
    role: "employee",
    salary: 5000,
  },
  {
    fname: "Rohit",
    lname: "Verma",
    email: "rohit.verma@example.com",
    password: "helloworldRohit",
    role: "admin",
  },
  {
    fname: "Sneha",
    lname: "Kumar",
    email: "sneha.kumar@example.com",
    password: "helloworldSneha",
    role: "employee",
    salary: 4500,
  },
  {
    fname: "Vikram",
    lname: "Malhotra",
    email: "vikram.malhotra@example.com",
    password: "helloworldVikram",
    role: "admin",
  },
  {
    fname: "Meera",
    lname: "Patel",
    email: "meera.patel@example.com",
    password: "helloworldMeera",
    role: "employee",
    salary: 4800,
  },
  {
    fname: "Karan",
    lname: "Sethi",
    email: "karan.sethi@example.com",
    password: "helloworldKaran",
    role: "employee",
    salary: 5200,
  },
  {
    fname: "Anjali",
    lname: "Nair",
    email: "anjali.nair@example.com",
    password: "helloworldAnjali",
    role: "admin",
  },
  {
    fname: "Rajesh",
    lname: "Kapoor",
    email: "rajesh.kapoor@example.com",
    password: "helloworldRajesh",
    role: "employee",
    salary: 4700,
  },
  {
    fname: "Neha",
    lname: "Aggarwal",
    email: "neha.aggarwal@example.com",
    password: "helloworldNeha",
    role: "admin",
  },
  {
    fname: "Arjun",
    lname: "Rao",
    email: "arjun.rao@example.com",
    password: "helloworldArjun",
    role: "employee",
    salary: 5100,
  },
];

const departments = ["IT", "MARKETING", "PRODUCTION", "NETWORKING"];

module.exports = { users, departments };
