const users = [
  {
    fname: "Ashok",
    lname: "Sharma",
    email: "ashok@gmail.com",
    password: "helloworldashok",
    role: "admin",
  },
  {
    fname: "Palak",
    lname: "Sharma",
    email: "palak@yahoo.com",
    password: "helloworldpalak",
    salary: 36000,
    role: "employee",
    department_id: 1,
  },
  {
    fname: "Raj",
    lname: "Lakhani",
    email: "raj@gmail.com",
    password: "helloworldraj",
    salary: 60000,
    role: "employee",
    department_id: 2,
  },
  {
    fname: "Priya",
    lname: "Singh",
    email: "priya.singh@example.com",
    password: "helloworldPriya",
    role: "employee",
    salary: 5000,
    department_id: 3,
  },
  {
    fname: "Rohit",
    lname: "Verma",
    email: "rohit.verma@example.com",
    password: "helloworldRohit",
    role: "admin",
  },
  {
    fname: "Sneha",
    lname: "Kumar",
    email: "sneha.kumar@example.com",
    password: "helloworldSneha",
    role: "employee",
    salary: 4500,
    department_id: 4,
  },
  {
    fname: "Vikram",
    lname: "Malhotra",
    email: "vikram.malhotra@example.com",
    password: "helloworldVikram",
    role: "admin",
  },
  {
    fname: "Meera",
    lname: "Patel",
    email: "meera.patel@example.com",
    password: "helloworldMeera",
    role: "employee",
    department_id: 1,
    salary: 4800,
  },
  {
    fname: "Karan",
    lname: "Sethi",
    email: "karan.sethi@example.com",
    password: "helloworldKaran",
    role: "employee",
    department_id: 4,
    salary: 5200,
  },
  {
    fname: "Anjali",
    lname: "Nair",
    email: "anjali.nair@example.com",
    password: "helloworldAnjali",
    role: "admin",
  },
  {
    fname: "Rajesh",
    lname: "Kapoor",
    email: "rajesh.kapoor@example.com",
    password: "helloworldRajesh",
    role: "employee",
    department_id: 3,
    salary: 4700,
  },
  {
    fname: "Neha",
    lname: "Aggarwal",
    email: "neha.aggarwal@example.com",
    password: "helloworldNeha",
    role: "admin",
  },
  {
    fname: "Arjun",
    lname: "Rao",
    email: "arjun.rao@example.com",
    password: "helloworldArjun",
    role: "employee",
    department_id: 1,
    salary: 5100,
  },
];

const departments = ["IT", "MARKETING", "PRODUCTION", "NETWORKING"];

const chartData = [
  { month: "January", Present: 85, Absence: 15 },
  { month: "February", Present: 75, Absence: 25 },
  { month: "March", Present: 80, Absence: 20 },
  { month: "April", Present: 78, Absence: 22 },
  { month: "May", Present: 95, Absence: 5 },
  { month: "June", Present: 82, Absence: 18 },
  { month: "July", Present: 88, Absence: 12 },
  { month: "August", Present: 87, Absence: 13 },
  { month: "September", Present: 92, Absence: 8 },
  { month: "October", Present: 85, Absence: 15 },
  { month: "November", Present: 89, Absence: 11 },
  { month: "December", Present: 91, Absence: 9 },
];

module.exports = { users, departments, chartData };
